import { useEffect, useState } from "react";
import { Link, useParams } from "wouter";
import { Layout, PageHeader } from "@/components/Layout";
import { BoundaryBanner, EvidenceCard, EvidenceStatusChip, EmptyEvidence } from "@/components/evidence/EvidencePrimitives";
import { evidenceApi } from "@/lib/evidenceApi";

export default function EvidenceTargetPage(){const {target}=useParams<{target:string}>();const [data,setData]=useState<any>();const [error,setError]=useState("");useEffect(()=>{evidenceApi.target(target).then(setData).catch(x=>setError(String(x)))},[target]);
return <Layout><PageHeader title={`${target.toUpperCase()} evidence profile`} subtitle="Independent registry retrieval; target association and AACR linkage are separate"/><div className="max-w-6xl mx-auto p-6 space-y-5"><BoundaryBanner/>{error&&<div className="text-red-300">{error}</div>}{!data&&!error&&<EmptyEvidence text="Loading governed evidence…"/>}{data&&<><div className="border border-amber-500/30 bg-amber-500/5 rounded p-4"><div className="flex items-center justify-between gap-3"><h2 className="font-mono font-bold">Association boundary</h2><EvidenceStatusChip status="LINKAGE_UNVERIFIED"/></div><p className="text-sm text-muted-foreground mt-2">{data.interpretation_boundary}</p><dl className="text-xs font-mono mt-3 grid md:grid-cols-2 gap-2"><div>Target association: <b>{data.target_association_state}</b></div><div>AACR linkage: <b>{data.aacr_abstract_linkage_state}</b></div></dl></div>
<section><h2 className="font-mono font-bold mb-3">Registry-returned studies ({data.studies.length})</h2>{data.studies.length?<div className="space-y-4">{data.studies.map((s:any)=><article key={s.nct_id} data-testid={`target-study-${s.nct_id}`} className="border border-border rounded bg-card p-4"><div className="flex justify-between items-center"><Link href={`/evidence/trials/${s.nct_id}`} className="font-mono font-bold text-primary hover:underline">{s.nct_id}</Link><EvidenceStatusChip status="LINKAGE_UNVERIFIED"/></div><p className="text-xs text-amber-200 mt-2">The registry fields below are verified; association with {target.toUpperCase()} remains query-retrieval evidence until separately confirmed.</p><div className="grid lg:grid-cols-2 gap-3 mt-4">{s.registry_facts.map((c:any)=><EvidenceCard key={c.receipt_id} claim={c}/>)}</div></article>)}</div>:<EmptyEvidence text="No registry retrieval records are available for this protocol."/>}</section></>}</div></Layout>}
