/**
 * deployMcp.ts — materialise a registered MCP as a Modal Web Function.
 *
 * Template: modal-labs/modal-examples/10_integrations/mcp_server_stateless.py
 * (verbatim FastMCP + Starlette + FastAPI shape, we substitute declared tools).
 *
 * Shadow mode (default): writes the generated modal_deploy.py under /tmp,
 * returns a fake modal.run URL that matches the real shape:
 *   https://openclaw--mcp-<slug>-web.modal.run/mcp/
 *
 * Live mode (MODAL_DRY_RUN unset, MODAL_TOKEN_ID + MODAL_TOKEN_SECRET set):
 * shells out to `modal deploy /tmp/openclaw-mcp-<slug>/modal_deploy.py`
 * and captures the printed URL from stdout.
 *
 * Zero secret spillage: we only pass env-var *names* into the generated
 * Python; the values live in Modal Secrets.
 */

import fs from "fs";
import path from "path";
import { spawnSync } from "child_process";
import { logger } from "../logger.js";
import type { RegistryMcp } from "../mcps/registry.js";

export interface DeployResult {
  deploy_id: string;
  modal_app_url: string;
  py_path: string;
  dry_run: boolean;
  logs: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Template — mirrors modal-labs/modal-examples/10_integrations/mcp_server_stateless.py
// ─────────────────────────────────────────────────────────────────────────────

function renderPython(mcp: RegistryMcp): string {
  const tools = (mcp.declaredTools as Array<{ name: string; description: string; input_schema: Record<string, unknown> }>) ?? [];
  const toolDefs = tools
    .map((t) => {
      // Very light param → Python kwargs conversion. Keeps type info as a docstring so
      // we don't need to run mypy in the deployed container.
      const params = Object.entries(t.input_schema ?? {})
        .map(([k, v]) => {
          const optional = typeof v === "string" && v.endsWith("?");
          const pyType = mapPyType(String(v).replace(/\?$/, ""));
          return `${k}: ${pyType}${optional ? " | None = None" : ""}`;
        })
        .join(", ");
      const paramDoc = Object.entries(t.input_schema ?? {})
        .map(([k, v]) => `        ${k}: ${v}`)
        .join("\n");
      return `
@mcp.tool()
def ${sanitize(t.name)}(${params}) -> dict:
    """${escapeDocstring(t.description)}

    Args:
${paramDoc || "        (none)"}
    """
    return {"tool": ${JSON.stringify(t.name)}, "args": locals(), "provider": ${JSON.stringify(mcp.slug)}}
`;
    })
    .join("\n");

  const envHints = ((mcp.declaredPrivileges as Record<string, string[]> | undefined)?.env ?? []).join(", ") || "(none declared)";

  return `# Auto-generated by OpenClaw Forge — do not hand-edit.
# Source MCP: ${mcp.slug} (${mcp.name})
# Template basis: modal-labs/modal-examples/10_integrations/mcp_server_stateless.py
# Declared env-var hints (never inline values): ${envHints}

import modal

image = modal.Image.debian_slim(python_version="3.12").pip_install(
    "fastmcp>=0.1.0", "fastapi", "starlette", "pydantic>=2.0"
)

app = modal.App("openclaw-mcp-${mcp.slug}")


def make_mcp_server():
    from fastmcp import FastMCP

    mcp = FastMCP("${mcp.slug}")
${toolDefs}
    return mcp


@app.function(image=image, timeout=300)
@modal.asgi_app()
def web():
    """Web gateway for the ${mcp.slug} MCP server."""
    from fastapi import FastAPI

    mcp = make_mcp_server()
    mcp_app = mcp.http_app(transport="streamable-http", stateless_http=True)

    fastapi_app = FastAPI(lifespan=mcp_app.router.lifespan_context)
    fastapi_app.mount("/", mcp_app, "mcp")

    @fastapi_app.get("/openclaw/health")
    def health():
        return {"ok": True, "mcp_slug": "${mcp.slug}", "n_tools": ${tools.length}}

    return fastapi_app


if __name__ == "__main__":
    # For local dev: modal serve modal_deploy.py
    pass
`;
}

function mapPyType(t: string): string {
  switch (t.toLowerCase()) {
    case "string":
      return "str";
    case "integer":
      return "int";
    case "number":
      return "float";
    case "boolean":
      return "bool";
    case "array":
      return "list";
    case "object":
      return "dict";
    default:
      return "str";
  }
}

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

function escapeDocstring(s: string): string {
  return s.replace(/"""/g, '\\"\\"\\"');
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

export async function deployMcpToModal(mcp: RegistryMcp): Promise<DeployResult> {
  const dry = process.env.MODAL_DRY_RUN !== "0";
  const slug = mcp.slug;
  const dir = path.join("/tmp", `openclaw-mcp-${slug}`);
  fs.mkdirSync(dir, { recursive: true });
  const py = path.join(dir, "modal_deploy.py");
  fs.writeFileSync(py, renderPython(mcp));

  const deploy_id = `${dry ? "dry-" : ""}deploy-${slug}-${Date.now()}`;
  const modal_app_url = `https://openclaw--mcp-${slug}-web.modal.run/mcp/`;

  if (dry) {
    logger.info({ slug, py, deploy_id }, "deployMcp: DRY_RUN — wrote modal_deploy.py, would deploy");
    return { deploy_id, modal_app_url, py_path: py, dry_run: true, logs: [`wrote ${py}`, "MODAL_DRY_RUN=1 — skipped modal deploy"] };
  }

  // Live path — requires modal CLI on PATH and valid credentials.
  logger.info({ slug, py }, "deployMcp: LIVE — invoking `modal deploy`");
  const proc = spawnSync("modal", ["deploy", py], {
    encoding: "utf-8",
    timeout: 5 * 60_000, // 5 min
    env: {
      ...process.env,
      MODAL_TOKEN_ID: process.env.MODAL_TOKEN_ID,
      MODAL_TOKEN_SECRET: process.env.MODAL_TOKEN_SECRET,
    },
  });
  const logs = [proc.stdout ?? "", proc.stderr ?? ""].filter(Boolean);
  if (proc.status !== 0) {
    throw new Error(`modal deploy failed (exit ${proc.status}): ${proc.stderr}`);
  }

  // Try to extract the printed URL; fall back to the projected shape
  const urlMatch = (proc.stdout ?? "").match(/https:\/\/[^\s]+modal\.run\/[^\s]*/);
  const detected_url = urlMatch ? urlMatch[0] : modal_app_url;

  return { deploy_id, modal_app_url: detected_url, py_path: py, dry_run: false, logs };
}

export async function healthCheck(): Promise<{ ok: boolean; mode: "dry" | "live"; token_present: boolean }> {
  const dry = process.env.MODAL_DRY_RUN !== "0";
  const token_present = Boolean(process.env.MODAL_TOKEN_ID && process.env.MODAL_TOKEN_SECRET);
  return { ok: true, mode: dry ? "dry" : "live", token_present };
}
