import type { DocClass } from "./draftReceiptEngine";

export const CLAUSE_LIBRARY_VERSION = "v1";

export interface ClauseVariant {
  variant_id: string;
  section: string;
  doc_class: DocClass | "all";
  label: string;
  body: string; // [PLACEHOLDER: field.path] markers allowed
  conditions: string[]; // documentation only
  jurisdiction_notes: Record<string, string>;
  approved_for_use: boolean;
  reviewed_by: string;
  last_reviewed_at: string; // ISO date
  risk_level: "standard" | "elevated" | "requires_counsel";
  allowed_jurisdictions: string[]; // ["*"] = all jurisdictions
}

// ── Selector ──────────────────────────────────────────────────────────────────
// Returns best approved variant for (section, doc_class, jurisdiction).
// Preference: exact doc_class match > "all"; standard risk > elevated.
// Returns null if no approved variant exists.
export function selectVariant(
  section: string,
  doc_class: DocClass,
  jurisdiction: string,
  library: ClauseVariant[],
): ClauseVariant | null {
  const candidates = library.filter(
    (v) =>
      v.section === section &&
      (v.doc_class === doc_class || v.doc_class === "all") &&
      v.approved_for_use &&
      (v.allowed_jurisdictions.includes("*") ||
        v.allowed_jurisdictions.includes(jurisdiction)),
  );
  if (candidates.length === 0) return null;

  const riskScore = (v: ClauseVariant): number =>
    v.risk_level === "standard" ? 2 : v.risk_level === "elevated" ? 1 : 0;
  const docScore = (v: ClauseVariant): number =>
    v.doc_class === doc_class ? 1 : 0;

  candidates.sort(
    (a, b) => docScore(b) - docScore(a) || riskScore(b) - riskScore(a),
  );
  return candidates[0];
}

// ── Clause library ────────────────────────────────────────────────────────────
// Built at module level from static data — never inside a function, never via require().
export const CLAUSE_LIBRARY: ClauseVariant[] = [
  // ── vesting_schedule ───────────────────────────────────────────────────────
  {
    variant_id: "VS-001",
    section: "vesting_schedule",
    doc_class: "all",
    label: "Vesting Schedule — 4yr/1yr cliff",
    body: "Equity shall vest over [PLACEHOLDER: equity.vesting_years] years, with a cliff of [PLACEHOLDER: equity.cliff_months] months. No equity vests before the cliff date. After the cliff, equity vests monthly in equal installments for the remainder of the vesting period.",
    conditions: ["vesting_years === 4", "cliff_months === 12"],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "VS-002",
    section: "vesting_schedule",
    doc_class: "all",
    label: "Vesting Schedule — 4yr/6mo cliff",
    body: "Equity shall vest over [PLACEHOLDER: equity.vesting_years] years, with a cliff of [PLACEHOLDER: equity.cliff_months] months. No equity vests before the cliff date. After the cliff, equity vests monthly in equal installments for the remainder of the vesting period.",
    conditions: ["vesting_years === 4", "cliff_months === 6"],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "VS-003",
    section: "vesting_schedule",
    doc_class: "all",
    label: "Vesting Schedule — 3yr/1yr cliff",
    body: "Equity shall vest over 3 years, with a cliff of 12 months. No equity vests before the cliff date. After the cliff, equity vests monthly in equal installments for the remainder of the vesting period.",
    conditions: ["vesting_years === 3", "cliff_months === 12"],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "VS-004",
    section: "vesting_schedule",
    doc_class: "all",
    label: "Vesting Schedule — 2yr/6mo cliff",
    body: "Equity shall vest over 2 years, with a cliff of 6 months. No equity vests before the cliff date. After the cliff, equity vests monthly in equal installments for the remainder of the vesting period.",
    conditions: ["vesting_years === 2", "cliff_months === 6"],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },

  // ── ip_assignment ──────────────────────────────────────────────────────────
  {
    variant_id: "IP-001",
    section: "ip_assignment",
    doc_class: "all",
    label: "IP Assignment — Broad (all inventions)",
    body: "Each party hereby irrevocably assigns to the Company all right, title, and interest in and to any and all inventions, discoveries, developments, improvements, works of authorship, and other intellectual property conceived, created, or reduced to practice during the term of this Agreement, whether or not patentable or copyrightable.",
    conditions: ["ip.scope === 'broad'"],
    jurisdiction_notes: {
      CA: "California Labor Code § 2870 limits assignment of inventions developed entirely on the employee's own time without use of company resources.",
      WA: "Washington RCW 49.44.140 contains similar limitations on IP assignment scope.",
    },
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "elevated",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "IP-002",
    section: "ip_assignment",
    doc_class: "contractor_ip_assignment",
    label: "IP Assignment — Work Product Only",
    body: "Contractor hereby irrevocably assigns to the Company all right, title, and interest in and to all work product, deliverables, and intellectual property created by Contractor specifically pursuant to the scope of work defined in this Agreement.",
    conditions: ["ip.scope === 'work_product_only'"],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "IP-003",
    section: "ip_assignment",
    doc_class: "co_founder_agreement",
    label: "IP Assignment — Broad with Prior Inventions Carve-Out",
    body: "Each party hereby irrevocably assigns to the Company all right, title, and interest in and to any and all inventions, discoveries, developments, improvements, works of authorship, and other intellectual property conceived, created, or reduced to practice during the term of this Agreement, except for those inventions listed in Schedule A (Prior Inventions) attached hereto.",
    conditions: ["ip.scope === 'broad'", "ip.prior_inventions present"],
    jurisdiction_notes: {
      CA: "California Labor Code § 2870 limits assignment of inventions developed entirely on the employee's own time without use of company resources.",
    },
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },

  // ── election_83b ───────────────────────────────────────────────────────────
  {
    variant_id: "83B-001",
    section: "election_83b",
    doc_class: "co_founder_agreement",
    label: "83(b) Election — Full Notice with Exhibit Reference",
    body: "Each party receiving equity subject to vesting acknowledges that they have been advised to file an election under Section 83(b) of the Internal Revenue Code within 30 days of the grant date. Failure to timely file will result in ordinary income recognition as equity vests. A form of 83(b) election is attached as Exhibit A. Filing must be made by certified mail with return receipt requested, and a copy must be retained by the electing party.",
    conditions: ["equity present", "vesting_schedule present"],
    jurisdiction_notes: {
      DE: "Delaware does not impose additional state-level requirements for 83(b) elections.",
      CA: "California conforms to federal 83(b) treatment. The 30-day window is absolute.",
    },
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    // 83(b) election has an absolute 30-day IRS filing window — time-critical, requires counsel.
    risk_level: "requires_counsel",
    allowed_jurisdictions: ["*"],
  },

  // ── governing_law ──────────────────────────────────────────────────────────
  {
    variant_id: "GL-DE",
    section: "governing_law",
    doc_class: "all",
    label: "Governing Law — Delaware",
    body: "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of laws principles. The parties consent to the exclusive jurisdiction of the state and federal courts located in Delaware.",
    conditions: ["jurisdiction === 'DE'"],
    jurisdiction_notes: {
      DE: "Delaware General Corporation Law (DGCL) § 152 requires board authorization for equity issuances.",
    },
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["DE"],
  },
  {
    variant_id: "GL-CA",
    section: "governing_law",
    doc_class: "all",
    label: "Governing Law — California",
    body: "This Agreement shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of laws principles. The parties consent to the exclusive jurisdiction of the state and federal courts located in California.",
    conditions: ["jurisdiction === 'CA'"],
    jurisdiction_notes: {
      CA: "California courts may apply California law regardless of choice-of-law clause for California residents.",
    },
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["CA"],
  },
  {
    variant_id: "GL-NY",
    section: "governing_law",
    doc_class: "all",
    label: "Governing Law — New York",
    body: "This Agreement shall be governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of laws principles. The parties consent to the exclusive jurisdiction of the state and federal courts located in New York.",
    conditions: ["jurisdiction === 'NY'"],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["NY"],
  },
  {
    variant_id: "GL-WA",
    section: "governing_law",
    doc_class: "all",
    label: "Governing Law — Washington",
    body: "This Agreement shall be governed by and construed in accordance with the laws of the State of Washington, without regard to its conflict of laws principles. The parties consent to the exclusive jurisdiction of the state and federal courts located in Washington.",
    conditions: ["jurisdiction === 'WA'"],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["WA"],
  },
  {
    variant_id: "GL-US",
    section: "governing_law",
    doc_class: "all",
    label: "Governing Law — Generic US",
    body: "This Agreement shall be governed by and construed in accordance with applicable federal law and the laws of the jurisdiction specified by the parties, without regard to conflict of laws principles.",
    conditions: ["jurisdiction not specifically listed"],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },

  // ── non_solicitation ───────────────────────────────────────────────────────
  {
    variant_id: "NS-001",
    section: "non_solicitation",
    doc_class: "all",
    label: "Non-Solicitation — 12 months",
    body: "For a period of 12 months following the termination of this Agreement, each party agrees not to directly solicit for employment any employee or contractor of the other party who was involved in the performance of this Agreement.",
    conditions: ["jurisdiction !== 'CA'"],
    jurisdiction_notes: {
      DE: "Enforceable in Delaware subject to reasonableness of scope and duration.",
      NY: "Enforceable in New York subject to reasonableness review.",
    },
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["DE", "NY", "WA", "TX"],
  },

  // ── deadlock_resolution ────────────────────────────────────────────────────
  {
    variant_id: "DR-001",
    section: "deadlock_resolution",
    doc_class: "co_founder_agreement",
    label: "Deadlock Resolution — Casting Vote (CEO/Lead Founder)",
    body: "In the event of a deadlock on any matter requiring unanimous consent of the founders, the Chief Executive Officer (or, if no CEO has been designated, the founder holding the largest equity stake) shall have a casting vote to resolve the deadlock.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },

  // ── acceleration_clause ────────────────────────────────────────────────────
  {
    variant_id: "ACC-001",
    section: "acceleration_clause",
    doc_class: "all",
    label: "Acceleration — Single Trigger (Change of Control)",
    body: "Upon a Change of Control (as defined herein), 100% of the unvested equity held by each party shall immediately vest. 'Change of Control' means any transaction in which a third party acquires more than 50% of the outstanding voting securities of the Company, or all or substantially all of the Company's assets.",
    conditions: ["equity.acceleration === 'single'"],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "ACC-002",
    section: "acceleration_clause",
    doc_class: "all",
    label: "Acceleration — Double Trigger (Change of Control + Termination)",
    body: "Upon a Change of Control followed by the involuntary termination of a party's service without Cause within 12 months of such Change of Control, 100% of that party's unvested equity shall immediately vest.",
    conditions: ["equity.acceleration === 'double'"],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },

  // ── Generic "all" variants for remaining required sections ─────────────────
  {
    variant_id: "PREAMBLE-001",
    section: "preamble",
    doc_class: "all",
    label: "Preamble",
    body: "This Agreement is entered into as of [PLACEHOLDER: effective_date] by and between the parties identified in the signature block below (collectively, the 'Parties').",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "EQ-SPLIT-001",
    section: "equity_split",
    doc_class: "co_founder_agreement",
    label: "Equity Split",
    body: "The Parties agree to the following equity allocation in the Company: [PLACEHOLDER: equity.split]. All equity grants are subject to the vesting schedule set forth herein and to board authorization as required by applicable law.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "ROLES-001",
    section: "roles_and_responsibilities",
    doc_class: "co_founder_agreement",
    label: "Roles and Responsibilities",
    body: "Each founder shall devote their full professional time and attention to the Company in the role designated in Schedule B. Roles may be amended by unanimous written consent of all founders.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "DM-001",
    section: "decision_making",
    doc_class: "co_founder_agreement",
    label: "Decision Making",
    body: "Ordinary business decisions shall be made by majority vote of the founders. Major decisions — including equity issuances, debt financing, asset sales, and changes to this Agreement — require unanimous written consent of all founders.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "TR-001",
    section: "transfer_restrictions",
    doc_class: "co_founder_agreement",
    label: "Transfer Restrictions",
    body: "No founder may transfer, sell, assign, pledge, or otherwise dispose of any equity interest in the Company without the prior written consent of all other founders and the Company's board of directors.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "TERM-BUYOUT-001",
    section: "termination_and_buyout",
    doc_class: "co_founder_agreement",
    label: "Termination and Buyout",
    body: "Upon a founder's departure from the Company for any reason, the Company shall have the right, but not the obligation, to repurchase any unvested equity at the original purchase price. Vested equity shall be subject to a right of first refusal in favor of the Company and remaining founders.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "SOW-001",
    section: "scope_of_work",
    doc_class: "contractor_ip_assignment",
    label: "Scope of Work",
    body: "Contractor shall perform the services described in the Statement of Work attached as Exhibit A, as may be amended by mutual written agreement of the parties.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "WMFH-001",
    section: "work_made_for_hire",
    doc_class: "contractor_ip_assignment",
    label: "Work Made for Hire",
    body: "To the extent permitted by applicable law, all work product created by Contractor under this Agreement shall be considered 'work made for hire' as defined in 17 U.S.C. § 101. To the extent any work product does not qualify as work made for hire, Contractor hereby assigns all rights therein to the Company.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "MRW-001",
    section: "moral_rights_waiver",
    doc_class: "contractor_ip_assignment",
    label: "Moral Rights Waiver",
    body: "To the fullest extent permitted by applicable law, Contractor hereby irrevocably waives any and all moral rights, rights of attribution, and rights of integrity in and to all work product created under this Agreement.",
    conditions: [],
    jurisdiction_notes: {
      CA: "17 U.S.C. § 106A moral rights apply to works of visual art. This waiver may not be effective for such works in California.",
    },
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "PIC-001",
    section: "prior_inventions_carveout",
    doc_class: "contractor_ip_assignment",
    label: "Prior Inventions Carve-Out",
    body: "The IP assignment in this Agreement does not apply to any inventions or intellectual property developed by Contractor prior to the commencement of this Agreement, as listed in Schedule A (Prior Inventions). Contractor represents that Schedule A is complete and accurate.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "CONF-001",
    section: "confidentiality",
    doc_class: "all",
    label: "Confidentiality",
    body: "Each party agrees to hold in strict confidence all Confidential Information of the other party and not to disclose such information to any third party without prior written consent. 'Confidential Information' means all non-public information disclosed by one party to the other in connection with this Agreement.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "RW-001",
    section: "representations_and_warranties",
    doc_class: "contractor_ip_assignment",
    label: "Representations and Warranties",
    body: "Contractor represents and warrants that: (a) Contractor has full authority to enter into this Agreement; (b) the work product will be original and will not infringe any third-party intellectual property rights; and (c) Contractor is not subject to any agreement that would conflict with this Agreement.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "ADV-SVC-001",
    section: "advisory_services",
    doc_class: "advisor_agreement",
    label: "Advisory Services",
    body: "Advisor agrees to provide the following advisory services to the Company: [PLACEHOLDER: advisory.services_description]. Advisor shall make themselves reasonably available to the Company's management team for consultation.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "EQ-COMP-001",
    section: "equity_compensation",
    doc_class: "advisor_agreement",
    label: "Equity Compensation",
    body: "As compensation for the advisory services, the Company shall grant Advisor equity representing [PLACEHOLDER: advisory.equity_pct]% of the Company's fully diluted capitalization, subject to the vesting schedule set forth herein and to board authorization as required by applicable law.",
    conditions: [],
    jurisdiction_notes: {
      DE: "DGCL § 152 requires board authorization prior to equity issuance.",
    },
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "NO-CONFLICT-001",
    section: "no_conflict",
    doc_class: "advisor_agreement",
    label: "No Conflict",
    body: "Advisor represents that Advisor is not subject to any agreement, obligation, or restriction that would conflict with or prevent Advisor from performing the advisory services or fulfilling Advisor's obligations under this Agreement.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "TERM-001",
    section: "termination",
    doc_class: "advisor_agreement",
    label: "Termination",
    body: "Either party may terminate this Agreement upon 30 days' written notice to the other party. Upon termination, Advisor's unvested equity shall be forfeited and the Company's repurchase right shall apply to any vested equity in accordance with the Company's standard equity agreements.",
    conditions: [],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
  {
    variant_id: "CASH-COMP-001",
    section: "cash_compensation",
    doc_class: "advisor_agreement",
    label: "Cash Compensation",
    body: "In addition to equity compensation, the Company shall pay Advisor a cash fee of $[PLACEHOLDER: advisory.cash_fee] per month, payable on the last business day of each month.",
    conditions: ["advisory.cash_fee present"],
    jurisdiction_notes: {},
    approved_for_use: true,
    reviewed_by: "template-review-v1",
    last_reviewed_at: "2026-01-01",
    risk_level: "standard",
    allowed_jurisdictions: ["*"],
  },
];
