import { Router, type Request, type Response } from "express";
import { pool } from "@workspace/db";
import { z } from "zod";
import { requireEvidenceIdentity, requireEvidenceRole } from "../lib/aacrEvidencePolicy.js";

const router=Router(); const BASE="/intelligence/evidence/reviews";
router.use(BASE,requireEvidenceIdentity);
const linkage=z.enum(["CONFIRMED_DIRECT_LINK","CONFIRMED_CONTEXTUAL_LINK","REAL_NCT_UNLINKED_TO_ABSTRACT","AMBIGUOUS_REVIEW_REQUIRED","NOT_FOUND"]);
const concordance=z.enum(["SUPPORTED","NOT_SUPPORTED","INSUFFICIENT_EVIDENCE"]);
const labelSchema=z.object({linkage_label:linkage,target_concordance:concordance,disease_concordance:concordance,intervention_concordance:concordance,rationale:z.string().min(10).max(4000)}).strict();
const adjudicationSchema=z.object({final_label:linkage,decision:z.enum(["PROMOTE","REJECT"]),rationale:z.string().min(10).max(4000)}).strict();

async function event(c:any,item:string,actor:string,type:string,from:string|null,to:string|null,payload:unknown,testOnly:boolean){
  await c.query(`INSERT INTO aacr_review_events(review_item_id,actor_id,event_type,from_state,to_state,payload_json,test_only) VALUES($1,$2,$3,$4,$5,$6,$7)`,[item,actor,type,from,to,JSON.stringify(payload??{}),testOnly]);
}
router.get(`${BASE}/queue`,requireEvidenceRole("ANNOTATOR","ADMIN"),async(req:Request,res:Response)=>{
  const user=req.evidenceIdentity!.userId; const result=await pool.query(`
    SELECT i.review_item_id,i.record_id,i.source_set_tags,i.state,i.priority,i.test_only,
      EXISTS(SELECT 1 FROM aacr_conflicts c WHERE c.record_id=i.record_id AND c.status='OPEN') has_conflict,
      (SELECT count(*)::int FROM aacr_review_assignments a WHERE a.review_item_id=i.review_item_id) assigned_slots
    FROM aacr_review_items i
    WHERE i.state NOT IN ('PROMOTED','REJECTED')
      AND NOT EXISTS(SELECT 1 FROM aacr_review_assignments a WHERE a.review_item_id=i.review_item_id AND a.reviewer_id=$1 AND a.status='SUBMITTED')
    ORDER BY i.priority DESC,i.created_at LIMIT 100`,[user]);
  res.json({items:result.rows,blinded:true,other_reviewer_labels_visible:false});
});
router.post(`${BASE}/:id/assign`,requireEvidenceRole("ADMIN"),async(req:Request,res:Response)=>{
  const parsed=z.object({reviewer_id:z.string().min(3),slot:z.union([z.literal(1),z.literal(2)])}).safeParse(req.body);
  if(!parsed.success){res.status(400).json({error:"INVALID_ASSIGNMENT",issues:parsed.error.issues});return;}
  const c=await pool.connect();try{await c.query("BEGIN");const item=await c.query(`SELECT * FROM aacr_review_items WHERE review_item_id=$1 FOR UPDATE`,[req.params.id]);if(!item.rowCount){await c.query("ROLLBACK");res.status(404).json({error:"REVIEW_ITEM_NOT_FOUND"});return;}
    const role=await c.query(`SELECT 1 FROM aacr_reviewer_roles WHERE user_id=$1 AND role='ANNOTATOR' AND active=true`,[parsed.data.reviewer_id]);if(!role.rowCount){await c.query("ROLLBACK");res.status(409).json({error:"REVIEWER_NOT_ACTIVE_ANNOTATOR"});return;}
    await c.query(`INSERT INTO aacr_review_assignments(review_item_id,reviewer_id,slot) VALUES($1,$2,$3)`,[req.params.id,parsed.data.reviewer_id,parsed.data.slot]);
    await c.query(`UPDATE aacr_review_items SET state='ASSIGNED' WHERE review_item_id=$1 AND state='UNASSIGNED'`,[req.params.id]);await event(c,req.params.id,req.evidenceIdentity!.userId,"ASSIGNED",item.rows[0].state,"ASSIGNED",{slot:parsed.data.slot,reviewer_id:parsed.data.reviewer_id},item.rows[0].test_only);await c.query("COMMIT");res.status(201).json({assigned:true});
  }catch(e:any){await c.query("ROLLBACK");res.status(e.code==="23505"?409:500).json({error:e.code==="23505"?"ASSIGNMENT_CONFLICT":"ASSIGNMENT_FAILED"});}finally{c.release();}
});
router.post(`${BASE}/:id/claim`,requireEvidenceRole("ANNOTATOR"),async(req:Request,res:Response)=>{
  const actor=req.evidenceIdentity!.userId;const c=await pool.connect();try{await c.query("BEGIN");const item=await c.query(`SELECT * FROM aacr_review_items WHERE review_item_id=$1 AND state NOT IN ('PROMOTED','REJECTED') FOR UPDATE`,[req.params.id]);if(!item.rowCount){await c.query("ROLLBACK");res.status(404).json({error:"REVIEW_ITEM_NOT_AVAILABLE"});return;}
    const previous=await c.query(`SELECT * FROM aacr_review_assignments WHERE review_item_id=$1 AND reviewer_id=$2`,[req.params.id,actor]);if(previous.rowCount){await c.query("ROLLBACK");res.status(409).json({error:"REVIEWER_ALREADY_ASSIGNED"});return;}
    const slots=await c.query(`SELECT slot FROM aacr_review_assignments WHERE review_item_id=$1 ORDER BY slot`,[req.params.id]);const used=new Set(slots.rows.map((x:any)=>x.slot));const slot=[1,2].find(x=>!used.has(x));if(!slot){await c.query("ROLLBACK");res.status(409).json({error:"INDEPENDENT_SLOTS_FULL"});return;}
    const assigned=await c.query(`INSERT INTO aacr_review_assignments(review_item_id,reviewer_id,slot,status,claimed_at) VALUES($1,$2,$3,'CLAIMED',now()) RETURNING assignment_id,slot`,[req.params.id,actor,slot]);
    await c.query(`UPDATE aacr_review_items SET state='INDEPENDENT_REVIEW' WHERE review_item_id=$1`,[req.params.id]);await event(c,req.params.id,actor,"CLAIMED",item.rows[0].state,"INDEPENDENT_REVIEW",{slot},item.rows[0].test_only);await c.query("COMMIT");res.json({assignment:assigned.rows[0],blinded:true});
  }catch{await c.query("ROLLBACK");res.status(500).json({error:"CLAIM_FAILED"});}finally{c.release();}
});
router.post(`${BASE}/:id/labels`,requireEvidenceRole("ANNOTATOR"),async(req:Request,res:Response)=>{
  const parsed=labelSchema.safeParse(req.body);if(!parsed.success){res.status(400).json({error:"INVALID_LABEL",issues:parsed.error.issues});return;}const actor=req.evidenceIdentity!.userId;const c=await pool.connect();try{await c.query("BEGIN");const item=await c.query(`SELECT * FROM aacr_review_items WHERE review_item_id=$1 FOR UPDATE`,[req.params.id]);const assignment=await c.query(`SELECT * FROM aacr_review_assignments WHERE review_item_id=$1 AND reviewer_id=$2 AND status IN ('ASSIGNED','CLAIMED')`,[req.params.id,actor]);if(!item.rowCount||!assignment.rowCount){await c.query("ROLLBACK");res.status(403).json({error:"ACTIVE_BLINDED_ASSIGNMENT_REQUIRED"});return;}
    await c.query(`INSERT INTO aacr_review_labels(review_item_id,assignment_id,reviewer_id,linkage_label,target_concordance,disease_concordance,intervention_concordance,rationale) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[req.params.id,assignment.rows[0].assignment_id,actor,parsed.data.linkage_label,parsed.data.target_concordance,parsed.data.disease_concordance,parsed.data.intervention_concordance,parsed.data.rationale]);await c.query(`UPDATE aacr_review_assignments SET status='SUBMITTED',submitted_at=now() WHERE assignment_id=$1`,[assignment.rows[0].assignment_id]);
    const labels=await c.query(`SELECT linkage_label FROM aacr_review_labels WHERE review_item_id=$1`,[req.params.id]);let to="INDEPENDENT_REVIEW";if(labels.rowCount===2&&labels.rows[0].linkage_label!==labels.rows[1].linkage_label)to="DISAGREEMENT";await c.query(`UPDATE aacr_review_items SET state=$2 WHERE review_item_id=$1`,[req.params.id,to]);await event(c,req.params.id,actor,"LABEL_SUBMITTED",item.rows[0].state,to,{assignment_slot:assignment.rows[0].slot},item.rows[0].test_only);await c.query("COMMIT");res.status(201).json({submitted:true,state:to,other_label_disclosed:false});
  }catch(e:any){await c.query("ROLLBACK");res.status(e.code==="23505"?409:500).json({error:e.code==="23505"?"LABEL_ALREADY_SUBMITTED":"LABEL_SUBMISSION_FAILED"});}finally{c.release();}
});
router.get(`${BASE}/adjudication-queue`,requireEvidenceRole("ADJUDICATOR","ADMIN"),async(req:Request,res:Response)=>{const result=await pool.query(`SELECT i.review_item_id,i.record_id,i.source_set_tags,i.state,jsonb_agg(jsonb_build_object('linkage_label',l.linkage_label,'target_concordance',l.target_concordance,'disease_concordance',l.disease_concordance,'intervention_concordance',l.intervention_concordance,'rationale',l.rationale) ORDER BY l.submitted_at) labels FROM aacr_review_items i JOIN aacr_review_labels l USING(review_item_id) WHERE i.state='DISAGREEMENT' GROUP BY i.review_item_id ORDER BY i.created_at`);res.json({items:result.rows});});
router.post(`${BASE}/:id/adjudicate`,requireEvidenceRole("ADJUDICATOR"),async(req:Request,res:Response)=>{const parsed=adjudicationSchema.safeParse(req.body);if(!parsed.success){res.status(400).json({error:"INVALID_ADJUDICATION",issues:parsed.error.issues});return;}const actor=req.evidenceIdentity!.userId;const c=await pool.connect();try{await c.query("BEGIN");const item=await c.query(`SELECT * FROM aacr_review_items WHERE review_item_id=$1 AND state='DISAGREEMENT' FOR UPDATE`,[req.params.id]);if(!item.rowCount){await c.query("ROLLBACK");res.status(409).json({error:"ITEM_NOT_IN_DISAGREEMENT"});return;}const conflict=await c.query(`SELECT 1 FROM aacr_review_labels WHERE review_item_id=$1 AND reviewer_id=$2`,[req.params.id,actor]);if(conflict.rowCount){await c.query("ROLLBACK");res.status(409).json({error:"ADJUDICATOR_MUST_BE_INDEPENDENT"});return;}
  await c.query(`INSERT INTO aacr_review_adjudications(review_item_id,adjudicator_id,final_label,decision,rationale) VALUES($1,$2,$3,$4,$5)`,[req.params.id,actor,parsed.data.final_label,parsed.data.decision,parsed.data.rationale]);await c.query(`UPDATE aacr_review_items SET state='ADJUDICATION' WHERE review_item_id=$1`,[req.params.id]);await event(c,req.params.id,actor,"ADJUDICATED","DISAGREEMENT","ADJUDICATION",{decision:parsed.data.decision,final_label:parsed.data.final_label},item.rows[0].test_only);await c.query("COMMIT");res.status(201).json({adjudicated:true});}catch(e:any){await c.query("ROLLBACK");res.status(e.code==="23505"?409:500).json({error:"ADJUDICATION_FAILED"});}finally{c.release();}});
async function decide(req:Request,res:Response,decision:"PROMOTED"|"REJECTED") {const actor=req.evidenceIdentity!.userId;const c=await pool.connect();try{await c.query("BEGIN");const item=await c.query(`SELECT * FROM aacr_review_items WHERE review_item_id=$1 FOR UPDATE`,[req.params.id]);if(!item.rowCount){await c.query("ROLLBACK");res.status(404).json({error:"REVIEW_ITEM_NOT_FOUND"});return;}const labels=await c.query(`SELECT DISTINCT reviewer_id,linkage_label FROM aacr_review_labels WHERE review_item_id=$1`,[req.params.id]);if(labels.rowCount!==2){await c.query("ROLLBACK");res.status(409).json({error:"TWO_DISTINCT_HUMAN_LABELS_REQUIRED"});return;}const disagree=labels.rows[0].linkage_label!==labels.rows[1].linkage_label;const adj=await c.query(`SELECT * FROM aacr_review_adjudications WHERE review_item_id=$1`,[req.params.id]);if(disagree&&!adj.rowCount){await c.query("ROLLBACK");res.status(409).json({error:"INDEPENDENT_ADJUDICATION_REQUIRED"});return;}if(decision==="PROMOTED"&&adj.rowCount&&adj.rows[0].decision!=="PROMOTE"){await c.query("ROLLBACK");res.status(409).json({error:"ADJUDICATION_REJECTS_PROMOTION"});return;}await c.query(`UPDATE aacr_review_items SET state=$2 WHERE review_item_id=$1`,[req.params.id,decision]);if(!item.rows[0].test_only&&decision==="PROMOTED")await c.query(`UPDATE aacr_abstracts SET human_qc_status='VERIFIED',permitted_use='INTERNAL_VALIDATED_SUBSET',updated_at=now() WHERE record_id=$1`,[item.rows[0].record_id]);await event(c,req.params.id,actor,decision,item.rows[0].state,decision,{production_promotion:!item.rows[0].test_only&&decision==="PROMOTED"},item.rows[0].test_only);await c.query("COMMIT");res.json({state:decision,production_promotion:!item.rows[0].test_only&&decision==="PROMOTED"});}catch{await c.query("ROLLBACK");res.status(500).json({error:"DECISION_FAILED"});}finally{c.release();}}
router.post(`${BASE}/:id/promote`,requireEvidenceRole("ADMIN"),(req,res)=>void decide(req,res,"PROMOTED"));
router.post(`${BASE}/:id/reject`,requireEvidenceRole("ADMIN"),(req,res)=>void decide(req,res,"REJECTED"));
router.get(`${BASE}/:id/events`,requireEvidenceRole("VIEWER","ANNOTATOR","ADJUDICATOR","ADMIN"),async(req,res)=>{const result=await pool.query(`SELECT * FROM aacr_review_events WHERE review_item_id=$1 ORDER BY created_at,event_id`,[req.params.id]);res.json({events:result.rows,append_only:true});});
router.post(`${BASE}/roles`,requireEvidenceRole("ADMIN"),async(req,res)=>{const parsed=z.object({user_id:z.string().min(3),role:z.enum(["VIEWER","ANNOTATOR","ADJUDICATOR","ADMIN"])}).safeParse(req.body);if(!parsed.success){res.status(400).json({error:"INVALID_ROLE"});return;}await pool.query(`INSERT INTO aacr_reviewer_roles(user_id,role,active) VALUES($1,$2,true) ON CONFLICT(user_id,role) DO UPDATE SET active=true`,[parsed.data.user_id,parsed.data.role]);res.status(201).json({assigned:true});});
export default router;
