import { Router, type IRouter } from "express";
import healthRouter from "./health";
import tenantsRouter from "./tenants";
import chatRouter from "./chat";
import connectorsRouter from "./connectors";
import graphsRouter from "./graphs";
import skillsRouter from "./skills";
import dashboardRouter from "./dashboard";
import billingRouter from "./billing";
import webhooksRouter from "./webhooks";
import forgeRouter from "./forge";
import legalRouter from "./legal";
import onboardingRouter from "./onboarding";
import manuscriptRouter from "./manuscript";
import seoRouter from "./seo";
import judgeRouter from "./judge";
import clauseDraftRouter from "./legal.clause.draft.js";
import flywheelRouter from "./flywheel.js";
import legalKbRouter from "./legal.kb.js";
import legalCounselRouter from "./legal.counsel.js";
import intelligenceRouter from "./intelligence.js";
import workflowsRouter from "./workflows.js";
import archonRouter from "./archon.js";
import statusRouter from "./status.js";
import localAuthRouter from "./localAuth.js";
import sovereignRouter from "./sovereign.js";
import corpusRouter from "./corpus.js";
import rigorRouter from "./rigor.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(tenantsRouter);
router.use(chatRouter);
router.use(connectorsRouter);
router.use(graphsRouter);
router.use(skillsRouter);
router.use(dashboardRouter);
router.use(billingRouter);
router.use(webhooksRouter);
router.use(forgeRouter);
router.use(legalRouter);
router.use(onboardingRouter);
router.use(manuscriptRouter);
router.use(seoRouter);
router.use(judgeRouter);
router.use(clauseDraftRouter);
router.use(flywheelRouter);
router.use(legalKbRouter);
router.use(legalCounselRouter);
router.use(intelligenceRouter);
router.use(workflowsRouter);
router.use(archonRouter);
router.use(statusRouter);
router.use("/auth", localAuthRouter);
router.use("/sovereign", sovereignRouter);
router.use("/corpus", corpusRouter);
router.use("/v1/rigor", rigorRouter);

export default router;
