import { Router, type IRouter } from "express";
import healthRouter from "./health";
import tenantsRouter from "./tenants";
import chatRouter from "./chat";
import connectorsRouter from "./connectors";
import graphsRouter from "./graphs";
import skillsRouter from "./skills";
import dashboardRouter from "./dashboard";
import billingRouter from "./billing";
import webhooksRouter from "./webhooks";
import forgeRouter from "./forge";
import legalRouter from "./legal";
import onboardingRouter from "./onboarding";
import manuscriptRouter from "./manuscript";
import seoRouter from "./seo";
import judgeRouter from "./judge";
import clauseDraftRouter from "./legal.clause.draft.js";
import flywheelRouter from "./flywheel.js";
import legalKbRouter from "./legal.kb.js";
import legalCounselRouter from "./legal.counsel.js";
import intelligenceRouter from "./intelligence.js";
import workflowsRouter from "./workflows.js";
import archonRouter from "./archon.js";
import stressBenchmarksRouter from "./stressBenchmarks.js";
import { mcpsRouter } from "./mcps.js";
import { mcpTrainingRouter } from "./mcpTraining.js";
import statusRouter from "./status.js";
import workflowRouter from "./workflow.js";
import loopRouter from "./loop.js";
import kriosRouter from "./krios.js";
import certifyRouter from "./certify.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(tenantsRouter);
router.use(chatRouter);
router.use(connectorsRouter);
router.use(graphsRouter);
router.use(skillsRouter);
router.use(dashboardRouter);
router.use(billingRouter);
router.use(webhooksRouter);
router.use(forgeRouter);
router.use(legalRouter);
router.use(onboardingRouter);
router.use(manuscriptRouter);
router.use(seoRouter);
router.use(judgeRouter);
router.use(clauseDraftRouter);
router.use(flywheelRouter);
router.use(legalKbRouter);
router.use(legalCounselRouter);
router.use(intelligenceRouter);
router.use(workflowsRouter);
router.use(archonRouter);
router.use(stressBenchmarksRouter);
router.use("/mcps", mcpsRouter);
router.use("/mcps/training", mcpTrainingRouter);
router.use(statusRouter);
router.use(workflowRouter);
router.use(loopRouter);
router.use(kriosRouter);
router.use(certifyRouter);
import regressionRouter from "./regression.js";
router.use(regressionRouter);
import archonTriageRouter from "./archon_triage.js";
router.use(archonTriageRouter);
import agentRouter from "./agent.js";
router.use(agentRouter);

export default router;
