/**
 * legal.draft.addendum.ts
 *
 * Route handlers for:
 *   POST /v1/legal/draft
 *   POST /v1/legal/draft/revise
 *
 * Mount instructions for legal.ts (minimal change only):
 *   1. Add imports at the top of legal.ts:
 *        import draftRouter from "./legal.draft.addendum";
 *   2. Before `export default router;` in legal.ts, add:
 *        router.use(draftRouter);
 *
 * The router in this file registers routes at /v1/legal/draft and
 * /v1/legal/draft/revise. The parent router in legal.ts is mounted at /api,
 * so the full paths become /api/v1/legal/draft and /api/v1/legal/draft/revise.
 */

import { Router, type Request, type Response } from "express";
import crypto from "crypto";
import {
  DraftArtifactStore,
  issueDraftReceipt,
  verifyDraftReceipt,
  hashText,
  type DraftIntake,
  type DraftRequestBody,
  type DocClass,
  type StoredDraftArtifact,
} from "../lib/draftReceiptEngine";
import { buildDraft, applyRevision, buildTitle, TEMPLATE_VERSION, CLAUSE_LIBRARY_VERSION } from "../lib/draftEngine";
import { verifyDraft, buildDraftGovernance, VERIFIER_VERSION } from "../lib/draftVerifier";
import { getTemplate } from "../lib/startupTemplates";

const router = Router();

const PRIVILEGE_WARNING =
  "This output is generated by an automated system and does not constitute legal advice. Review by qualified counsel is required before execution.";

const VALID_DOC_CLASSES: DocClass[] = [
  "co_founder_agreement",
  "contractor_ip_assignment",
  "advisor_agreement",
];

// ── POST /v1/legal/draft ──────────────────────────────────────────────────────
router.post("/v1/legal/draft", async (req: Request, res: Response) => {
  const start = Date.now();

  try {
    const body = req.body as DraftRequestBody;

    // 501: model rewrite stub
    if (body.allow_model_clause_rewrite === true) {
      return res.status(501).json({
        error: "not_implemented",
        message: "allow_model_clause_rewrite is not supported in v0",
      });
    }

    // 400: validate required fields
    if (!body.doc_class || !VALID_DOC_CLASSES.includes(body.doc_class as DocClass)) {
      return res.status(400).json({
        error: "invalid_doc_class",
        message: `doc_class must be one of: ${VALID_DOC_CLASSES.join(", ")}`,
      });
    }
    if (!body.jurisdiction || body.jurisdiction.trim() === "") {
      return res.status(400).json({
        error: "missing_field",
        message: "jurisdiction is required",
      });
    }
    if (!Array.isArray(body.parties) || body.parties.length < 2) {
      return res.status(400).json({
        error: "invalid_parties",
        message: "parties must be an array with at least 2 entries",
      });
    }
    for (const p of body.parties) {
      if (!p.name || !p.role) {
        return res.status(400).json({
          error: "invalid_party",
          message: "each party must have name and role",
        });
      }
    }

    const intake = body as DraftIntake;

    // Build draft
    const buildResult = buildDraft(intake);

    // Verify
    const verifierResult = verifyDraft(buildResult, intake);
    const governance = buildDraftGovernance(verifierResult);

    // Persist artifact
    const draft_id = crypto.randomUUID();
    const template = getTemplate(intake.doc_class);
    const title = buildTitle(template.title_template, intake);

    const artifact: StoredDraftArtifact = {
      draft_id,
      parent_draft_id: null,
      receipt_id: "", // filled after issueDraftReceipt
      doc_class: intake.doc_class,
      intake,
      sections: buildResult.sections,
      full_text: buildResult.full_text,
      section_map: buildResult.section_map,
      assumptions: buildResult.assumptions,
      missing_info_flags: buildResult.missing_info_flags,
      verifier_result: verifierResult,
      governance_artifact_status: governance.artifact_status,
      revision_number: 0,
      created_at: new Date().toISOString(),
    };

    const secret = process.env.SESSION_SECRET ?? "dev-secret";
    const draft_receipt_token = issueDraftReceipt({
      draft_id,
      doc_class: intake.doc_class,
      full_text: buildResult.full_text,
      intake,
      template_version: TEMPLATE_VERSION,
      clause_library_version: CLAUSE_LIBRARY_VERSION,
      verifier_version: VERIFIER_VERSION,
      governance_artifact_status: governance.artifact_status,
      parent_receipt_id: null,
      secret,
    });

    // Back-fill receipt_id from token (decode to get receipt_id)
    const verified = verifyDraftReceipt(draft_receipt_token, secret);
    if (verified.valid) {
      artifact.receipt_id = verified.receipt.receipt_id;
    }

    DraftArtifactStore.put(artifact);

    return res.status(200).json({
      draft_id,
      draft_receipt_token,
      doc_class: intake.doc_class,
      draft: {
        title,
        sections: buildResult.sections,
        full_text: buildResult.full_text,
      },
      section_map: buildResult.section_map,
      assumptions: buildResult.assumptions,
      missing_info_flags: buildResult.missing_info_flags,
      missing_decision_prompts: buildResult.missing_decision_prompts,   // v0.5
      verifier: verifierResult,
      governance: {
        artifact_status: governance.artifact_status,
        escalation_required: governance.escalation_required,
        review_threshold: governance.review_threshold,                  // v0.5
        human_review_required: true as const,
        not_legal_advice: true as const,
        privilege_warning: PRIVILEGE_WARNING,
      },
      trace: {
        draft_id,
        doc_class: intake.doc_class,
        template_version: TEMPLATE_VERSION,
        clause_library_version: CLAUSE_LIBRARY_VERSION,
        verifier_version: VERIFIER_VERSION,
        model_used: null,
        model_clause_rewrite: false as const,
        latency_ms: Date.now() - start,
      },
    });
  } catch (err) {
    console.error("[legal.draft] unexpected error", err);
    return res.status(500).json({ error: "internal_error" });
  }
});

// ── POST /v1/legal/draft/revise ───────────────────────────────────────────────
router.post("/v1/legal/draft/revise", async (req: Request, res: Response) => {
  const start = Date.now();

  try {
    const { draft_receipt_token, revision_instruction } = req.body as {
      draft_receipt_token?: string;
      revision_instruction?: string;
    };

    // 400: missing required fields
    if (!draft_receipt_token || !revision_instruction) {
      return res.status(400).json({
        error: "missing_field",
        message: "draft_receipt_token and revision_instruction are required",
      });
    }

    // 501: model rewrite stub
    if ((req.body as Record<string, unknown>).allow_model_clause_rewrite === true) {
      return res.status(501).json({
        error: "not_implemented",
        message: "allow_model_clause_rewrite is not supported in v0",
      });
    }

    const secret = process.env.SESSION_SECRET ?? "dev-secret";

    // Step 2: verify token
    const verification = verifyDraftReceipt(draft_receipt_token, secret);
    if (!verification.valid) {
      return res.status(401).json({
        error: "invalid_token",
        reason: verification.reason,
      });
    }
    const receipt = verification.receipt;

    // Step 3: load artifact
    const stored = DraftArtifactStore.get(receipt.draft_id);
    if (!stored) {
      return res.status(404).json({
        error: "draft_not_found",
        message: `draft_id ${receipt.draft_id} not found`,
      });
    }

    // Step 4: verify intake integrity
    const storedIntakeHash = hashText(JSON.stringify(stored.intake));
    if (storedIntakeHash !== receipt.intake_hash) {
      return res.status(400).json({
        error: "intake_hash_mismatch",
        message: "Stored intake does not match receipt — artifact may be corrupted",
      });
    }

    // Step 5: apply revision
    const revisionResult = applyRevision(stored, revision_instruction, false);


    // Step 5b: reject unparseable instructions — do not silently return 200
    if (revisionResult.missing_info_flags.includes("revision_instruction_not_parseable")) {
      return res.status(422).json({
        error: "instruction_not_parseable",
        message: "The revision_instruction could not be applied. Supported patterns: vesting change (e.g. \"change vesting to 3 years with a 1-year cliff\"), governing law change, section removal.",
        revision_instruction,
      });
    }
    // Step 6: re-verify
    const verifierResult = verifyDraft(
      {
        sections: revisionResult.new_sections,
        full_text: revisionResult.new_full_text,
        section_map: revisionResult.new_section_map,
        assumptions: revisionResult.assumptions,
        missing_info_flags: revisionResult.missing_info_flags,
        missing_decision_prompts: [],
      },
      stored.intake,
    );

    // Step 7: governance
    const governance = buildDraftGovernance(verifierResult);

    // Step 8: persist new artifact
    const new_draft_id = crypto.randomUUID();
    const template = getTemplate(stored.intake.doc_class);
    const title = buildTitle(template.title_template, stored.intake);

    const newArtifact: StoredDraftArtifact = {
      draft_id: new_draft_id,
      parent_draft_id: receipt.draft_id,
      receipt_id: "", // filled after issueDraftReceipt
      doc_class: stored.intake.doc_class,
      intake: stored.intake, // trusted — from store, not client
      sections: revisionResult.new_sections,
      full_text: revisionResult.new_full_text,
      section_map: revisionResult.new_section_map,
      assumptions: revisionResult.assumptions,
      missing_info_flags: revisionResult.missing_info_flags,
      verifier_result: verifierResult,
      governance_artifact_status: governance.artifact_status,
      revision_number: stored.revision_number + 1,
      created_at: new Date().toISOString(),
    };

    // Step 9: sign new receipt
    const new_receipt_token = issueDraftReceipt({
      draft_id: new_draft_id,
      doc_class: stored.intake.doc_class,
      full_text: revisionResult.new_full_text,
      intake: stored.intake,
      template_version: TEMPLATE_VERSION,
      clause_library_version: CLAUSE_LIBRARY_VERSION,
      verifier_version: VERIFIER_VERSION,
      governance_artifact_status: governance.artifact_status,
      parent_receipt_id: receipt.receipt_id,
      secret,
    });

    const newVerified = verifyDraftReceipt(new_receipt_token, secret);
    if (newVerified.valid) {
      newArtifact.receipt_id = newVerified.receipt.receipt_id;
    }

    DraftArtifactStore.put(newArtifact);

    return res.status(200).json({
      draft_id: new_draft_id,
      draft_receipt_token: new_receipt_token,
      doc_class: stored.intake.doc_class,
      draft: {
        title,
        sections: revisionResult.new_sections,
        full_text: revisionResult.new_full_text,
      },
      section_map: revisionResult.new_section_map,
      assumptions: revisionResult.assumptions,
      missing_info_flags: revisionResult.missing_info_flags,
      missing_decision_prompts: [],                                      // v0.5 — revision path: prompts not regenerated
      verifier: verifierResult,
      governance: {
        artifact_status: governance.artifact_status,
        escalation_required: governance.escalation_required,
        review_threshold: governance.review_threshold,                  // v0.5
        human_review_required: true as const,
        not_legal_advice: true as const,
        privilege_warning: PRIVILEGE_WARNING,
      },
      trace: {
        draft_id: new_draft_id,
        doc_class: stored.intake.doc_class,
        template_version: TEMPLATE_VERSION,
        clause_library_version: CLAUSE_LIBRARY_VERSION,
        verifier_version: VERIFIER_VERSION,
        model_used: null,
        model_clause_rewrite: false as const,
        latency_ms: Date.now() - start,
      },
      parent_receipt_id: receipt.receipt_id,
      revision_number: newArtifact.revision_number,
    });
  } catch (err) {
    console.error("[legal.draft.revise] unexpected error", err);
    return res.status(500).json({ error: "internal_error" });
  }
});

export default router;
