/**
 * legal.draft.addendum.ts
 *
 * Route handlers for:
 *   POST /v1/legal/draft
 *   POST /v1/legal/draft/revise
 *
 * Mount instructions for legal.ts (minimal change only):
 *   1. Add imports at the top of legal.ts:
 *        import draftRouter from "./legal.draft.addendum";
 *   2. Before `export default router;` in legal.ts, add:
 *        router.use(draftRouter);
 *
 * The router in this file registers routes at /v1/legal/draft and
 * /v1/legal/draft/revise. The parent router in legal.ts is mounted at /api,
 * so the full paths become /api/v1/legal/draft and /api/v1/legal/draft/revise.
 */

import { Router, type Request, type Response } from "express";
import crypto from "crypto";
import {
  DraftArtifactStore,
  issueDraftReceipt,
  verifyDraftReceipt,
  hashText,
  type DraftIntake,
  type DraftRequestBody,
  type DocClass,
  type StoredDraftArtifact,
} from "../lib/draftReceiptEngine";
import { buildDraft, applyRevision, buildTitle, TEMPLATE_VERSION, CLAUSE_LIBRARY_VERSION } from "../lib/draftEngine";
import { verifyDraft, buildDraftGovernance, VERIFIER_VERSION } from "../lib/draftVerifier";
import { getTemplate } from "../lib/startupTemplates";
import { extractIntakeFromText } from "../lib/contractExtractor";
import { normalizeExtractedIntake } from "../lib/contractNormalizer";
import type { UncertainField } from "../lib/contractExtractor";

const router = Router();
// ── Safe-default substitution for normalized intake ──────────────────────────
// Mirrors the logic in contractExtractor.ts but operates on normalized_intake.

const SAFE_DEFAULTS_NORMALIZER: Record<string, unknown> = {
  "equity.vesting_years":  4,
  "equity.cliff_months":   12,
  "equity.acceleration":   "none",
  "ip.scope":              "broad",
  "jurisdiction":          "DE",
};

function applyDotPathNorm(obj: Record<string, unknown>, path: string, value: unknown): void {
  const parts = path.split(".");
  let cur: Record<string, unknown> = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (cur[parts[i]] == null || typeof cur[parts[i]] !== "object") {
      cur[parts[i]] = {};
    }
    cur = cur[parts[i]] as Record<string, unknown>;
  }
  cur[parts[parts.length - 1]] = value;
}

function applyNormalizerSafeDefaults(
  intake: import("../lib/draftReceiptEngine").DraftIntake,
  uncertainFields: UncertainField[],
): import("../lib/draftReceiptEngine").DraftIntake {
  const ready = JSON.parse(JSON.stringify(intake));
  for (const uf of uncertainFields) {
    if (uf.confidence < 0.6) {
      const safeDefault = SAFE_DEFAULTS_NORMALIZER[uf.field];
      if (safeDefault !== undefined) {
        applyDotPathNorm(ready, uf.field, safeDefault);
      }
    }
  }
  return ready;
}



const PRIVILEGE_WARNING =
  "This output is generated by an automated system and does not constitute legal advice. Review by qualified counsel is required before execution.";

const VALID_DOC_CLASSES: DocClass[] = [
  "co_founder_agreement",
  "contractor_ip_assignment",
  "advisor_agreement",
];

// ── POST /v1/legal/draft ──────────────────────────────────────────────────────
router.post("/v1/legal/draft", async (req: Request, res: Response) => {
  const start = Date.now();

  try {
    const body = req.body as DraftRequestBody;

    // 501: model rewrite stub
    if (body.allow_model_clause_rewrite === true) {
      return res.status(501).json({
        error: "not_implemented",
        message: "allow_model_clause_rewrite is not supported in v0",
      });
    }

    // 400: validate required fields
    if (!body.doc_class || !VALID_DOC_CLASSES.includes(body.doc_class as DocClass)) {
      return res.status(400).json({
        error: "invalid_doc_class",
        message: `doc_class must be one of: ${VALID_DOC_CLASSES.join(", ")}`,
      });
    }
    if (!body.jurisdiction || body.jurisdiction.trim() === "") {
      return res.status(400).json({
        error: "missing_field",
        message: "jurisdiction is required",
      });
    }
    if (!Array.isArray(body.parties) || body.parties.length < 2) {
      return res.status(400).json({
        error: "invalid_parties",
        message: "parties must be an array with at least 2 entries",
      });
    }
    for (const p of body.parties) {
      if (!p.name || !p.role) {
        return res.status(400).json({
          error: "invalid_party",
          message: "each party must have name and role",
        });
      }
    }

    const intake = body as DraftIntake;

    // Build draft
    const buildResult = buildDraft(intake);

    // Verify
    const verifierResult = verifyDraft(buildResult, intake);
    const governance = buildDraftGovernance(verifierResult);

    // Persist artifact
    const draft_id = crypto.randomUUID();
    const template = getTemplate(intake.doc_class);
    const title = buildTitle(template.title_template, intake);

    const artifact: StoredDraftArtifact = {
      draft_id,
      parent_draft_id: null,
      receipt_id: "", // filled after issueDraftReceipt
      doc_class: intake.doc_class,
      intake,
      sections: buildResult.sections,
      full_text: buildResult.full_text,
      section_map: buildResult.section_map,
      assumptions: buildResult.assumptions,
      missing_info_flags: buildResult.missing_info_flags,
      verifier_result: verifierResult,
      governance_artifact_status: governance.artifact_status,
      revision_number: 0,
      created_at: new Date().toISOString(),
    };

    const secret = process.env.SESSION_SECRET ?? "dev-secret";
    const draft_receipt_token = issueDraftReceipt({
      draft_id,
      doc_class: intake.doc_class,
      full_text: buildResult.full_text,
      intake,
      template_version: TEMPLATE_VERSION,
      clause_library_version: CLAUSE_LIBRARY_VERSION,
      verifier_version: VERIFIER_VERSION,
      governance_artifact_status: governance.artifact_status,
      parent_receipt_id: null,
      secret,
    });

    // Back-fill receipt_id from token (decode to get receipt_id)
    const verified = verifyDraftReceipt(draft_receipt_token, secret);
    if (verified.valid) {
      artifact.receipt_id = verified.receipt.receipt_id;
    }

    DraftArtifactStore.put(artifact);

    return res.status(200).json({
      draft_id,
      draft_receipt_token,
      doc_class: intake.doc_class,
      draft: {
        title,
        sections: buildResult.sections,
        full_text: buildResult.full_text,
      },
      section_map: buildResult.section_map,
      assumptions: buildResult.assumptions,
      missing_info_flags: buildResult.missing_info_flags,
      missing_decision_prompts: buildResult.missing_decision_prompts,   // v0.5
      verifier: verifierResult,
      governance: {
        artifact_status: governance.artifact_status,
        escalation_required: governance.escalation_required,
        review_threshold: governance.review_threshold,                  // v0.5
        human_review_required: true as const,
        not_legal_advice: true as const,
        privilege_warning: PRIVILEGE_WARNING,
      },
      trace: {
        draft_id,
        doc_class: intake.doc_class,
        template_version: TEMPLATE_VERSION,
        clause_library_version: CLAUSE_LIBRARY_VERSION,
        verifier_version: VERIFIER_VERSION,
        model_used: null,
        model_clause_rewrite: false as const,
        latency_ms: Date.now() - start,
      },
    });
  } catch (err) {
    console.error("[legal.draft] unexpected error", err);
    return res.status(500).json({ error: "internal_error" });
  }
});

// ── POST /v1/legal/draft/revise ───────────────────────────────────────────────
router.post("/v1/legal/draft/revise", async (req: Request, res: Response) => {
  const start = Date.now();

  try {
    const { draft_receipt_token, revision_instruction } = req.body as {
      draft_receipt_token?: string;
      revision_instruction?: string;
    };

    // 400: missing required fields
    if (!draft_receipt_token || !revision_instruction) {
      return res.status(400).json({
        error: "missing_field",
        message: "draft_receipt_token and revision_instruction are required",
      });
    }

    // 501: model rewrite stub
    if ((req.body as Record<string, unknown>).allow_model_clause_rewrite === true) {
      return res.status(501).json({
        error: "not_implemented",
        message: "allow_model_clause_rewrite is not supported in v0",
      });
    }

    const secret = process.env.SESSION_SECRET ?? "dev-secret";

    // Step 2: verify token
    const verification = verifyDraftReceipt(draft_receipt_token, secret);
    if (!verification.valid) {
      return res.status(401).json({
        error: "invalid_token",
        reason: verification.reason,
      });
    }
    const receipt = verification.receipt;

    // Step 3: load artifact
    const stored = DraftArtifactStore.get(receipt.draft_id);
    if (!stored) {
      return res.status(404).json({
        error: "draft_not_found",
        message: `draft_id ${receipt.draft_id} not found`,
      });
    }

    // Step 4: verify intake integrity
    const storedIntakeHash = hashText(JSON.stringify(stored.intake));
    if (storedIntakeHash !== receipt.intake_hash) {
      return res.status(400).json({
        error: "intake_hash_mismatch",
        message: "Stored intake does not match receipt — artifact may be corrupted",
      });
    }

    // Step 5: apply revision
    const revisionResult = applyRevision(stored, revision_instruction, false);


    // Step 5b: reject unparseable instructions — do not silently return 200
    if (revisionResult.missing_info_flags.includes("revision_instruction_not_parseable")) {
      return res.status(422).json({
        error: "instruction_not_parseable",
        message: "The revision_instruction could not be applied. Supported patterns: vesting change (e.g. \"change vesting to 3 years with a 1-year cliff\"), governing law change, section removal.",
        revision_instruction,
      });
    }
    // Step 6: re-verify
    const verifierResult = verifyDraft(
      {
        sections: revisionResult.new_sections,
        full_text: revisionResult.new_full_text,
        section_map: revisionResult.new_section_map,
        assumptions: revisionResult.assumptions,
        missing_info_flags: revisionResult.missing_info_flags,
        missing_decision_prompts: [],
      },
      stored.intake,
    );

    // Step 7: governance
    const governance = buildDraftGovernance(verifierResult);

    // Step 8: persist new artifact
    const new_draft_id = crypto.randomUUID();
    const template = getTemplate(stored.intake.doc_class);
    const title = buildTitle(template.title_template, stored.intake);

    const newArtifact: StoredDraftArtifact = {
      draft_id: new_draft_id,
      parent_draft_id: receipt.draft_id,
      receipt_id: "", // filled after issueDraftReceipt
      doc_class: stored.intake.doc_class,
      intake: stored.intake, // trusted — from store, not client
      sections: revisionResult.new_sections,
      full_text: revisionResult.new_full_text,
      section_map: revisionResult.new_section_map,
      assumptions: revisionResult.assumptions,
      missing_info_flags: revisionResult.missing_info_flags,
      verifier_result: verifierResult,
      governance_artifact_status: governance.artifact_status,
      revision_number: stored.revision_number + 1,
      created_at: new Date().toISOString(),
    };

    // Step 9: sign new receipt
    const new_receipt_token = issueDraftReceipt({
      draft_id: new_draft_id,
      doc_class: stored.intake.doc_class,
      full_text: revisionResult.new_full_text,
      intake: stored.intake,
      template_version: TEMPLATE_VERSION,
      clause_library_version: CLAUSE_LIBRARY_VERSION,
      verifier_version: VERIFIER_VERSION,
      governance_artifact_status: governance.artifact_status,
      parent_receipt_id: receipt.receipt_id,
      secret,
    });

    const newVerified = verifyDraftReceipt(new_receipt_token, secret);
    if (newVerified.valid) {
      newArtifact.receipt_id = newVerified.receipt.receipt_id;
    }

    DraftArtifactStore.put(newArtifact);

    return res.status(200).json({
      draft_id: new_draft_id,
      draft_receipt_token: new_receipt_token,
      doc_class: stored.intake.doc_class,
      draft: {
        title,
        sections: revisionResult.new_sections,
        full_text: revisionResult.new_full_text,
      },
      section_map: revisionResult.new_section_map,
      assumptions: revisionResult.assumptions,
      missing_info_flags: revisionResult.missing_info_flags,
      missing_decision_prompts: [],                                      // v0.5 — revision path: prompts not regenerated
      verifier: verifierResult,
      governance: {
        artifact_status: governance.artifact_status,
        escalation_required: governance.escalation_required,
        review_threshold: governance.review_threshold,                  // v0.5
        human_review_required: true as const,
        not_legal_advice: true as const,
        privilege_warning: PRIVILEGE_WARNING,
      },
      trace: {
        draft_id: new_draft_id,
        doc_class: stored.intake.doc_class,
        template_version: TEMPLATE_VERSION,
        clause_library_version: CLAUSE_LIBRARY_VERSION,
        verifier_version: VERIFIER_VERSION,
        model_used: null,
        model_clause_rewrite: false as const,
        latency_ms: Date.now() - start,
      },
      parent_receipt_id: receipt.receipt_id,
      revision_number: newArtifact.revision_number,
    });
  } catch (err) {
    console.error("[legal.draft.revise] unexpected error", err);
    return res.status(500).json({ error: "internal_error" });
  }
});


// ── POST /v1/legal/draft/analyze ─────────────────────────────────────────────
router.post("/v1/legal/draft/analyze", async (req: Request, res: Response) => {
  const start = Date.now();

  try {
    const { contract_text, doc_class } = req.body as {
      contract_text?: unknown;
      doc_class?: unknown;
    };

    // ── Validate contract_text ──────────────────────────────────────────────
    if (typeof contract_text !== "string" || contract_text.length === 0) {
      return res.status(422).json({
        error: "invalid_input",
        message: "contract_text required",
      });
    }
    if (contract_text.length < 50) {
      return res.status(422).json({
        error: "invalid_input",
        message: "contract_text too short (min 50 chars)",
      });
    }
    if (contract_text.length > 50_000) {
      return res.status(422).json({
        error: "invalid_input",
        message: "contract_text too long (max 50000 chars)",
      });
    }

    // ── Validate doc_class ──────────────────────────────────────────────────
    if (!doc_class || !VALID_DOC_CLASSES.includes(doc_class as DocClass)) {
      return res.status(422).json({
        error: "invalid_input",
        message: `doc_class required; must be one of: ${VALID_DOC_CLASSES.join(", ")}`,
      });
    }

    const validDocClass = doc_class as DocClass;

    // ── 1. Extract ──────────────────────────────────────────────────────────
    const extractResult = await extractIntakeFromText(contract_text, validDocClass);

    // ── 2. Normalize ────────────────────────────────────────────────────────
    const normalizeResult = normalizeExtractedIntake(
      extractResult.intake,
      validDocClass,
      extractResult.uncertain_fields,
    );

    // ── 3. Build draft from normalized + safe-defaulted intake ──────────────
    const draftReadyIntake = applyNormalizerSafeDefaults(
      normalizeResult.normalized_intake,
      normalizeResult.uncertain_fields,
    );
    const buildResult = buildDraft(draftReadyIntake);

    // ── 4. Verify ───────────────────────────────────────────────────────────
    const verifierResult = verifyDraft(buildResult, draftReadyIntake);

    // ── 5. Governance ───────────────────────────────────────────────────────
    const governanceResult = buildDraftGovernance(verifierResult);

    // ── 6. Compose response ─────────────────────────────────────────────────
    const analysis_id = crypto.randomUUID();
    const sourceHash  = hashText(contract_text).slice(0, 16);

    const redraft_available =
      extractResult.extraction_confidence >= 0.5 && verifierResult.passed;

    return res.status(200).json({
      analysis_id,
      doc_class: validDocClass,
      source: {
        length: contract_text.length,
        hash:   sourceHash,
        text:   contract_text,
      },
      // Extraction
      raw_extracted_intake:  extractResult.intake,
      extraction_confidence: extractResult.extraction_confidence,
      // Normalization
      normalized_intake:        normalizeResult.normalized_intake,
      normalization_notes:      normalizeResult.normalization_notes,
      normalization_summary:    normalizeResult.normalization_summary,
      not_applicable_fields:    normalizeResult.not_applicable_fields,
      missing_required_fields:  normalizeResult.missing_required_fields,
      uncertain_fields:         normalizeResult.uncertain_fields,
      // Draft pipeline
      draft_ready_intake:       draftReadyIntake,
      sections:                 buildResult.sections,
      assumptions:              buildResult.assumptions,
      missing_decision_prompts: buildResult.missing_decision_prompts,
      verifier:                 verifierResult,
      governance: {
        review_threshold:  governanceResult.review_threshold,
        artifact_status:   governanceResult.artifact_status,
        not_legal_advice:  true,
        privilege_warning: PRIVILEGE_WARNING,
      },
      redraft_available,
      trace: {
        latency_ms:    Date.now() - start,
        model_used:    extractResult.model_used,
        fallback_used: extractResult.fallback_used,
      },
    });
  } catch (err) {
    console.error("[legal.draft.analyze] unexpected error", err);
    return res.status(500).json({ error: "internal_error" });
  }
});

export default router;
