/**
 * bundleGenerator.ts — sovereign (on-prem / air-gapped) deployment bundle generator.
 *
 * Generates a complete, self-contained deployment package a tenant can run in
 * their own environment (VPC, on-prem, isolated tenant) with NO public-cloud
 * dependency: local Postgres, local Qdrant, locally-hosted LLM (Ollama), the
 * OpenClaw API, and the front-end — wired together with local auth.
 *
 * This is the V2 moat: a hedge fund / hospital / compliance-bound tenant gets
 * the full platform inside their perimeter, driven from the front-end.
 *
 * Output: a set of files (compose, env template, Dockerfiles, scripts, README)
 * returned as a map { path -> content } and packaged as a tarball by the route.
 */

export interface SovereignConfig {
  tenantName: string;          // e.g. "acme-capital"
  domain?: string;             // e.g. "openclaw.acme.internal" (optional; default localhost)
  llmBackend: "local" | "hybrid";  // local = fully air-gapped; hybrid = local-first + cloud fallback
  localChatModel: string;      // e.g. "llama3.1:8b"
  localEmbedModel: string;     // e.g. "nomic-embed-text"
  authProvider: "local";       // sovereign always uses local auth (no Clerk)
  apiPort: number;             // default 3001
  webPort: number;             // default 8080
  enableGpu: boolean;          // pass GPU to Ollama
}

export interface BundleFile {
  path: string;
  content: string;
  executable?: boolean;
}

export function defaultSovereignConfig(tenantName: string): SovereignConfig {
  return {
    tenantName: tenantName.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "") || "tenant",
    domain: "localhost",
    llmBackend: "local",
    localChatModel: "llama3.1:8b",
    localEmbedModel: "nomic-embed-text",
    authProvider: "local",
    apiPort: 3001,
    webPort: 8080,
    enableGpu: false,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Templates
// ─────────────────────────────────────────────────────────────────────────────

function dockerCompose(c: SovereignConfig): string {
  const gpuReserve = c.enableGpu
    ? `        deploy:\n          resources:\n            reservations:\n              devices:\n                - driver: nvidia\n                  count: all\n                  capabilities: [gpu]\n`
    : "";
  return `# OpenClaw Sovereign Deployment — ${c.tenantName}
# Generated by OpenClaw. Self-contained: no public-cloud dependency.
# Services: Postgres (data), Qdrant (vectors), Ollama (local LLM), API, Web.

version: "3.9"

networks:
  openclaw:
    driver: bridge

volumes:
  pgdata:
  qdrantdata:
  ollamadata:

services:
  postgres:
    image: postgres:16-alpine
    container_name: ${c.tenantName}-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: openclaw
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: openclaw
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [openclaw]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openclaw"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ${c.tenantName}-qdrant
    restart: unless-stopped
    volumes:
      - qdrantdata:/qdrant/storage
    networks: [openclaw]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:6333/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ${c.tenantName}-ollama
    restart: unless-stopped
    volumes:
      - ollamadata:/root/.ollama
${gpuReserve}    networks: [openclaw]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:11434/api/tags || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ${c.tenantName}-api
    restart: unless-stopped
    depends_on:
      postgres: { condition: service_healthy }
      qdrant: { condition: service_healthy }
      ollama: { condition: service_healthy }
    environment:
      NODE_ENV: production
      PORT: "3001"
      DATABASE_URL: postgresql://openclaw:\${POSTGRES_PASSWORD}@postgres:5432/openclaw
      QDRANT_URL: http://qdrant:6333
      QDRANT_API_KEY: ""
      AUTH_PROVIDER: local
      LOCAL_AUTH_SECRET: \${LOCAL_AUTH_SECRET}
      LLM_BACKEND: ${c.llmBackend}
      EMBED_BACKEND: ${c.llmBackend === "hybrid" ? "hybrid" : "local"}
      LOCAL_LLM_BASE_URL: http://ollama:11434
      LOCAL_LLM_MODEL: ${c.localChatModel}
      LOCAL_EMBED_MODEL: ${c.localEmbedModel}
      LOCAL_EMBED_DIMS: \${LOCAL_EMBED_DIMS:-768}
      OPENCLAW_ADMIN_TOKEN: \${OPENCLAW_ADMIN_TOKEN}
      OPENCLAW_SERVICE_TOKEN: \${OPENCLAW_SERVICE_TOKEN}
      FRONTEND_URL: http://localhost:${c.webPort}
      CORS_ORIGIN: http://localhost:${c.webPort}
      # Cloud fallback keys (only used when LLM_BACKEND=hybrid). Leave empty for air-gapped.
      GOOGLE_API_KEY: \${GOOGLE_API_KEY:-}
      GROQ_API_KEY: \${GROQ_API_KEY:-}
      LEGAL_CORPUS_BOOT_SEED: "false"
      DRY_RUN: "false"
    ports:
      - "${c.apiPort}:3001"
    networks: [openclaw]

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:${c.apiPort}
    container_name: ${c.tenantName}-web
    restart: unless-stopped
    depends_on: [api]
    ports:
      - "${c.webPort}:80"
    networks: [openclaw]
`;
}

function envTemplate(c: SovereignConfig): string {
  return `# OpenClaw Sovereign — ${c.tenantName} environment
# Copy to .env and fill in secrets before \`docker compose up\`.

# REQUIRED — generate strong random values:
#   openssl rand -hex 32
POSTGRES_PASSWORD=
LOCAL_AUTH_SECRET=
OPENCLAW_ADMIN_TOKEN=
OPENCLAW_SERVICE_TOKEN=

# Local LLM embedding dims (nomic-embed-text=768, mxbai-embed-large=1024)
LOCAL_EMBED_DIMS=768

# OPTIONAL — only used when LLM_BACKEND=hybrid (cloud fallback). Leave empty for air-gapped.
GOOGLE_API_KEY=
GROQ_API_KEY=
`;
}

function apiDockerfile(): string {
  return `# OpenClaw API — sovereign build
FROM node:20-alpine AS build
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@9 --activate
COPY . .
RUN pnpm install --no-frozen-lockfile
RUN pnpm --filter @workspace/api-server run build

FROM node:20-alpine
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@9 --activate
COPY --from=build /app .
EXPOSE 3001
CMD ["node", "artifacts/api-server/dist/index.mjs"]
`;
}

function webDockerfile(): string {
  return `# OpenClaw Web — sovereign build
FROM node:20-alpine AS build
WORKDIR /app
ARG VITE_API_URL
ENV VITE_API_URL=\${VITE_API_URL}
RUN corepack enable && corepack prepare pnpm@9 --activate
COPY . .
RUN pnpm install --no-frozen-lockfile
RUN pnpm --filter @workspace/openclaw-saas run build

FROM nginx:alpine
COPY --from=build /app/artifacts/openclaw-saas/dist/public /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
}

function nginxConf(): string {
  return `server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  location / {
    try_files $uri $uri/ /index.html;
  }
  location /api/ {
    proxy_pass http://api:3001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
`;
}

function setupScript(c: SovereignConfig): string {
  return `#!/usr/bin/env bash
# OpenClaw Sovereign setup — ${c.tenantName}
set -euo pipefail
cd "$(dirname "$0")"

if [ ! -f .env ]; then
  echo "ERROR: .env not found. Copy env.template to .env and fill in secrets."
  exit 1
fi

echo "==> Building images"
docker compose build

echo "==> Starting Postgres, Qdrant, Ollama"
docker compose up -d postgres qdrant ollama

echo "==> Waiting for Ollama to be ready"
until docker compose exec -T ollama wget -qO- http://localhost:11434/api/tags >/dev/null 2>&1; do
  sleep 2
done

echo "==> Pulling local models: ${c.localChatModel}, ${c.localEmbedModel}"
docker compose exec -T ollama ollama pull ${c.localChatModel} || true
docker compose exec -T ollama ollama pull ${c.localEmbedModel} || true

echo "==> Starting API + Web"
docker compose up -d api web

echo "==> Running DB migrations"
sleep 5
curl -fsS -X POST "http://localhost:${c.apiPort}/api/admin/migrate" \\
  -H "Authorization: Bearer $(grep OPENCLAW_SERVICE_TOKEN .env | cut -d= -f2)" || \\
  echo "(migration runs automatically on boot; this is a belt-and-suspenders trigger)"

echo ""
echo "OpenClaw sovereign deployment is up:"
echo "  Web:  http://localhost:${c.webPort}"
echo "  API:  http://localhost:${c.apiPort}/api/healthz"
echo ""
echo "Create the first (admin) user:"
echo "  curl -X POST http://localhost:${c.apiPort}/api/auth/local/register \\\\"
echo "    -H 'Content-Type: application/json' \\\\"
echo "    -d '{\\"email\\":\\"admin@example.com\\",\\"password\\":\\"<strong-password>\\"}'"
`;
}

function backupScript(): string {
  return `#!/usr/bin/env bash
# Backup Postgres + Qdrant volumes to ./backups/<timestamp>/
set -euo pipefail
cd "$(dirname "$0")"
TS=$(date +%Y%m%d-%H%M%S)
mkdir -p "backups/$TS"
echo "==> Backing up Postgres"
docker compose exec -T postgres pg_dump -U openclaw openclaw | gzip > "backups/$TS/postgres.sql.gz"
echo "==> Backing up Qdrant"
docker run --rm --volumes-from "$(docker compose ps -q qdrant)" -v "$PWD/backups/$TS:/backup" alpine \\
  tar czf /backup/qdrant-storage.tar.gz -C /qdrant/storage .
echo "Backup complete: backups/$TS/"
`;
}

function readme(c: SovereignConfig): string {
  return `# OpenClaw Sovereign Deployment — ${c.tenantName}

A self-contained, air-gapped deployment of the OpenClaw platform. Everything
runs inside your perimeter: database, vector store, LLM, API, and front-end.
**No public-cloud dependency** when \`LLM_BACKEND=local\`.

## What's in the box

| Service | Image | Purpose |
|---------|-------|---------|
| postgres | postgres:16-alpine | relational data + BM25 full-text |
| qdrant | qdrant/qdrant | vector store (semantic retrieval) |
| ollama | ollama/ollama | locally-hosted LLM (chat + embeddings) |
| api | (built) | OpenClaw API server |
| web | (built) | OpenClaw front-end |

## Prerequisites

- Docker + Docker Compose v2
- ~16 GB RAM free (more if \`enableGpu=false\` and models run on CPU)
- (Optional) NVIDIA GPU + nvidia-container-toolkit for faster local inference

## Quick start

1. **Configure secrets**
   \`\`\`bash
   cp env.template .env
   # Generate strong values:
   sed -i "s/^POSTGRES_PASSWORD=$/POSTGRES_PASSWORD=$(openssl rand -hex 32)/" .env
   sed -i "s/^LOCAL_AUTH_SECRET=$/LOCAL_AUTH_SECRET=$(openssl rand -hex 32)/" .env
   sed -i "s/^OPENCLAW_ADMIN_TOKEN=$/OPENCLAW_ADMIN_TOKEN=$(openssl rand -hex 24)/" .env
   sed -i "s/^OPENCLAW_SERVICE_TOKEN=$/OPENCLAW_SERVICE_TOKEN=$(openssl rand -hex 24)/" .env
   \`\`\`

2. **Copy the application source** into \`api/\` and \`web/\` build contexts
   (see "Source layout" below), then:

3. **Launch**
   \`\`\`bash
   ./setup.sh
   \`\`\`

4. **Create the first admin user** (printed by setup.sh), then log in at
   \`http://localhost:${c.webPort}\`.

## Configuration

- **LLM backend**: \`${c.llmBackend}\`
  - \`local\` — fully air-gapped; all chat + embeddings via Ollama.
  - \`hybrid\` — local-first with cloud (Gemini/Groq) fallback. Requires
    \`GOOGLE_API_KEY\` / \`GROQ_API_KEY\` in \`.env\`.
- **Models**: chat \`${c.localChatModel}\`, embeddings \`${c.localEmbedModel}\`.
  Change in \`docker-compose.yml\` and re-run \`./setup.sh\`.
- **Auth**: local HMAC-JWT provider (no Clerk). First registered user is admin.

## Source layout

The compose build contexts expect the OpenClaw repo at:
- \`api/\` — full repo (Dockerfile builds \`@workspace/api-server\`)
- \`web/\` — full repo (Dockerfile builds \`@workspace/openclaw-saas\`)

Copy or clone the repo into both contexts (they build independent targets), or
adjust the \`build.context\` paths in \`docker-compose.yml\` to point at a single
checkout.

## Operations

- **Backup**: \`./backup.sh\` → \`backups/<timestamp>/\`
- **Logs**: \`docker compose logs -f api\`
- **Stop**: \`docker compose down\` (add \`-v\` to also wipe data volumes)
- **Upgrade**: replace source in \`api/\` + \`web/\`, then \`docker compose build && docker compose up -d\`

## Security notes

- All inter-service traffic is on an isolated Docker bridge network.
- Only the API (${c.apiPort}) and Web (${c.webPort}) ports are exposed; Postgres,
  Qdrant, and Ollama are internal-only.
- Local auth uses PBKDF2-hashed passwords + HMAC-SHA256 JWTs. Set a strong
  \`LOCAL_AUTH_SECRET\` and rotate \`OPENCLAW_ADMIN_TOKEN\` periodically.
- For a VPC deployment, place the Web/API behind your existing reverse proxy /
  SSO and do not expose them publicly.
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

export function generateSovereignBundle(config: Partial<SovereignConfig> & { tenantName: string }): BundleFile[] {
  const c: SovereignConfig = { ...defaultSovereignConfig(config.tenantName), ...config };
  return [
    { path: "docker-compose.yml", content: dockerCompose(c) },
    { path: "env.template", content: envTemplate(c) },
    { path: "api/Dockerfile", content: apiDockerfile() },
    { path: "web/Dockerfile", content: webDockerfile() },
    { path: "web/nginx.conf", content: nginxConf() },
    { path: "setup.sh", content: setupScript(c), executable: true },
    { path: "backup.sh", content: backupScript(), executable: true },
    { path: "README.md", content: readme(c) },
  ];
}
